services:
  mini-kafka:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mini-kafka
    ports:
      - "9092:9092"
    volumes:
      - mini-kafka-data:/var/lib/mini-kafka

volumes:
  mini-kafka-data:
